//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Settings/Input/BoardInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BoardInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BoardInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BoardInput"",
    ""maps"": [
        {
            ""name"": ""Board"",
            ""id"": ""b45bc684-1a2d-46dc-889b-23070c217772"",
            ""actions"": [
                {
                    ""name"": ""Clear"",
                    ""type"": ""Button"",
                    ""id"": ""c2ba927c-c1ea-4a56-b56e-213e5b0b7444"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetNumber1"",
                    ""type"": ""Button"",
                    ""id"": ""4e578e01-7974-43bb-aa73-ffb1892ccc06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetNumber2"",
                    ""type"": ""Button"",
                    ""id"": ""e5cd80c1-2cdf-4abc-a9ae-2f8ec911e8d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetNumber3"",
                    ""type"": ""Button"",
                    ""id"": ""8a993f41-682b-483f-b7ae-fc6a4ca9f995"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetNumber4"",
                    ""type"": ""Button"",
                    ""id"": ""08ffee84-03ef-4283-9855-6eb6e9f393d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetNumber5"",
                    ""type"": ""Button"",
                    ""id"": ""a785bf98-031f-4ab7-9d2b-0d9288336c77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetNumber6"",
                    ""type"": ""Button"",
                    ""id"": ""6a52661f-1b11-4232-9355-7deb72d711ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetNumber7"",
                    ""type"": ""Button"",
                    ""id"": ""a5b2f5d6-483b-4c73-9555-b0e3f52eac92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetNumber8"",
                    ""type"": ""Button"",
                    ""id"": ""0918bb9f-d0cb-4ff6-87e8-498edf179c35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetNumber9"",
                    ""type"": ""Button"",
                    ""id"": ""8ed29518-63ce-4360-8323-e91ba53947d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""92d3a1fc-3a66-49cf-a80c-1b87b3769205"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b620130-c10e-4f07-ab99-113f4397627a"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76d4cf3d-6ead-4a17-b308-b99166ca2a2b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetNumber1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3548f0e2-dd02-43fd-a3df-6fb5333c8c5c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetNumber2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c069327-d301-4b71-86dd-f98cd1bed470"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetNumber3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8abadf96-b79c-420e-84d2-7c5f8711bfb1"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetNumber4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efd6cfb0-7f99-4bf8-90f6-e702716cc557"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetNumber5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2cb2665-be80-47f7-8163-55d33e4eaf5f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetNumber6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94d10a37-7512-42a8-be8e-958ee4b22d3c"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetNumber7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dc2cd0d-d098-4e20-9c11-d91490069530"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetNumber8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0f71bbe-9e84-4c1b-9948-8d39dc5ec059"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetNumber9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Board
        m_Board = asset.FindActionMap("Board", throwIfNotFound: true);
        m_Board_Clear = m_Board.FindAction("Clear", throwIfNotFound: true);
        m_Board_SetNumber1 = m_Board.FindAction("SetNumber1", throwIfNotFound: true);
        m_Board_SetNumber2 = m_Board.FindAction("SetNumber2", throwIfNotFound: true);
        m_Board_SetNumber3 = m_Board.FindAction("SetNumber3", throwIfNotFound: true);
        m_Board_SetNumber4 = m_Board.FindAction("SetNumber4", throwIfNotFound: true);
        m_Board_SetNumber5 = m_Board.FindAction("SetNumber5", throwIfNotFound: true);
        m_Board_SetNumber6 = m_Board.FindAction("SetNumber6", throwIfNotFound: true);
        m_Board_SetNumber7 = m_Board.FindAction("SetNumber7", throwIfNotFound: true);
        m_Board_SetNumber8 = m_Board.FindAction("SetNumber8", throwIfNotFound: true);
        m_Board_SetNumber9 = m_Board.FindAction("SetNumber9", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Board
    private readonly InputActionMap m_Board;
    private List<IBoardActions> m_BoardActionsCallbackInterfaces = new List<IBoardActions>();
    private readonly InputAction m_Board_Clear;
    private readonly InputAction m_Board_SetNumber1;
    private readonly InputAction m_Board_SetNumber2;
    private readonly InputAction m_Board_SetNumber3;
    private readonly InputAction m_Board_SetNumber4;
    private readonly InputAction m_Board_SetNumber5;
    private readonly InputAction m_Board_SetNumber6;
    private readonly InputAction m_Board_SetNumber7;
    private readonly InputAction m_Board_SetNumber8;
    private readonly InputAction m_Board_SetNumber9;
    public struct BoardActions
    {
        private @BoardInput m_Wrapper;
        public BoardActions(@BoardInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Clear => m_Wrapper.m_Board_Clear;
        public InputAction @SetNumber1 => m_Wrapper.m_Board_SetNumber1;
        public InputAction @SetNumber2 => m_Wrapper.m_Board_SetNumber2;
        public InputAction @SetNumber3 => m_Wrapper.m_Board_SetNumber3;
        public InputAction @SetNumber4 => m_Wrapper.m_Board_SetNumber4;
        public InputAction @SetNumber5 => m_Wrapper.m_Board_SetNumber5;
        public InputAction @SetNumber6 => m_Wrapper.m_Board_SetNumber6;
        public InputAction @SetNumber7 => m_Wrapper.m_Board_SetNumber7;
        public InputAction @SetNumber8 => m_Wrapper.m_Board_SetNumber8;
        public InputAction @SetNumber9 => m_Wrapper.m_Board_SetNumber9;
        public InputActionMap Get() { return m_Wrapper.m_Board; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BoardActions set) { return set.Get(); }
        public void AddCallbacks(IBoardActions instance)
        {
            if (instance == null || m_Wrapper.m_BoardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BoardActionsCallbackInterfaces.Add(instance);
            @Clear.started += instance.OnClear;
            @Clear.performed += instance.OnClear;
            @Clear.canceled += instance.OnClear;
            @SetNumber1.started += instance.OnSetNumber1;
            @SetNumber1.performed += instance.OnSetNumber1;
            @SetNumber1.canceled += instance.OnSetNumber1;
            @SetNumber2.started += instance.OnSetNumber2;
            @SetNumber2.performed += instance.OnSetNumber2;
            @SetNumber2.canceled += instance.OnSetNumber2;
            @SetNumber3.started += instance.OnSetNumber3;
            @SetNumber3.performed += instance.OnSetNumber3;
            @SetNumber3.canceled += instance.OnSetNumber3;
            @SetNumber4.started += instance.OnSetNumber4;
            @SetNumber4.performed += instance.OnSetNumber4;
            @SetNumber4.canceled += instance.OnSetNumber4;
            @SetNumber5.started += instance.OnSetNumber5;
            @SetNumber5.performed += instance.OnSetNumber5;
            @SetNumber5.canceled += instance.OnSetNumber5;
            @SetNumber6.started += instance.OnSetNumber6;
            @SetNumber6.performed += instance.OnSetNumber6;
            @SetNumber6.canceled += instance.OnSetNumber6;
            @SetNumber7.started += instance.OnSetNumber7;
            @SetNumber7.performed += instance.OnSetNumber7;
            @SetNumber7.canceled += instance.OnSetNumber7;
            @SetNumber8.started += instance.OnSetNumber8;
            @SetNumber8.performed += instance.OnSetNumber8;
            @SetNumber8.canceled += instance.OnSetNumber8;
            @SetNumber9.started += instance.OnSetNumber9;
            @SetNumber9.performed += instance.OnSetNumber9;
            @SetNumber9.canceled += instance.OnSetNumber9;
        }

        private void UnregisterCallbacks(IBoardActions instance)
        {
            @Clear.started -= instance.OnClear;
            @Clear.performed -= instance.OnClear;
            @Clear.canceled -= instance.OnClear;
            @SetNumber1.started -= instance.OnSetNumber1;
            @SetNumber1.performed -= instance.OnSetNumber1;
            @SetNumber1.canceled -= instance.OnSetNumber1;
            @SetNumber2.started -= instance.OnSetNumber2;
            @SetNumber2.performed -= instance.OnSetNumber2;
            @SetNumber2.canceled -= instance.OnSetNumber2;
            @SetNumber3.started -= instance.OnSetNumber3;
            @SetNumber3.performed -= instance.OnSetNumber3;
            @SetNumber3.canceled -= instance.OnSetNumber3;
            @SetNumber4.started -= instance.OnSetNumber4;
            @SetNumber4.performed -= instance.OnSetNumber4;
            @SetNumber4.canceled -= instance.OnSetNumber4;
            @SetNumber5.started -= instance.OnSetNumber5;
            @SetNumber5.performed -= instance.OnSetNumber5;
            @SetNumber5.canceled -= instance.OnSetNumber5;
            @SetNumber6.started -= instance.OnSetNumber6;
            @SetNumber6.performed -= instance.OnSetNumber6;
            @SetNumber6.canceled -= instance.OnSetNumber6;
            @SetNumber7.started -= instance.OnSetNumber7;
            @SetNumber7.performed -= instance.OnSetNumber7;
            @SetNumber7.canceled -= instance.OnSetNumber7;
            @SetNumber8.started -= instance.OnSetNumber8;
            @SetNumber8.performed -= instance.OnSetNumber8;
            @SetNumber8.canceled -= instance.OnSetNumber8;
            @SetNumber9.started -= instance.OnSetNumber9;
            @SetNumber9.performed -= instance.OnSetNumber9;
            @SetNumber9.canceled -= instance.OnSetNumber9;
        }

        public void RemoveCallbacks(IBoardActions instance)
        {
            if (m_Wrapper.m_BoardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBoardActions instance)
        {
            foreach (var item in m_Wrapper.m_BoardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BoardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BoardActions @Board => new BoardActions(this);
    public interface IBoardActions
    {
        void OnClear(InputAction.CallbackContext context);
        void OnSetNumber1(InputAction.CallbackContext context);
        void OnSetNumber2(InputAction.CallbackContext context);
        void OnSetNumber3(InputAction.CallbackContext context);
        void OnSetNumber4(InputAction.CallbackContext context);
        void OnSetNumber5(InputAction.CallbackContext context);
        void OnSetNumber6(InputAction.CallbackContext context);
        void OnSetNumber7(InputAction.CallbackContext context);
        void OnSetNumber8(InputAction.CallbackContext context);
        void OnSetNumber9(InputAction.CallbackContext context);
    }
}
